version: '3.1'
services:

  backend:
    image: maven:3.6.3-jdk-8
    command: mvn spring-boot:run
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - 5000:5000
      - 5005:5005
    volumes:
      - .:/usr/src/mymaven:rw
    working_dir: /usr/src/mymaven

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplerootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - 3306:3306
    # volumes:
    #   - ./src/db-setup.sql:/docker-entrypoint-initdb.d/dump.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080